// Copy for /glaucoma. Designed configuration.

export const GLAUCOMA = {
  title: "ARKA · Glaucoma: older adults",
  header: {
    title: "Glaucoma",
    cohort: "Older adults",
    status: "designed" as const,
    illustrationAlt: "An older adult seated by a bright window.",
    ribbonLabel: "Light ribbon: a single daytime bright-light target",
    lede: "Three things on screen. Large type. Text with every icon. Nothing that is colour alone.",
  },
  goals: [
    { text: "Daytime bright-light exposure", refs: ["kawasaki2021"] },
    { text: "Eye-drop adherence", refs: ["buehne2021"] },
    { text: "Follow-up attendance", refs: ["leiby2021"] },
  ],
  why: {
    kicker: "Why light matters here",
    heading: "Glaucoma reaches the body clock.",
    nodes: [
      { label: "Glaucoma damages the eye" },
      { label: "ipRGC loss", refs: ["feigl2011"] },
      { label: "Light no longer sets the body clock" },
      { label: "Dysregulated circadian rhythm" },
      { label: "Reduced quality of life", refs: ["dirani2009", "feigl2011"] },
    ],
    body: "The same cells that carry light to the clock are lost in glaucoma. A daytime bright-light target is designed to give the remaining cells a stronger signal.",
  },
  home: {
    kicker: "Home is three things",
    heading: "Bright light. Eye drops. Next appointment.",
    body: "Greeting by name, one large number, one plain bar, the remainder in words. Then a 64-pixel button for the evening drops. Then the next appointment. Nothing else above the fold.",
    greeting: "Good morning, Mrs Tan",
    minutes: 84,
    target: 120,
    minutesLabel: "Bright light today",
    remaining: "36 min remaining",
    drops: { label: "Eye drops", time: "8:00 PM", button: "Mark as done", done: "✓ Done" },
    appointment: { label: "Next appointment", date: "12 Oct", time: "10:30 AM" },
    tabs: ["Home", "Insights", "Inbox", "Lumi"],
    redundancy: {
      heading: "The redundancy rule",
      body: "Applies to every screen in this configuration: status is never colour alone.",
      pairs: [
        { bad: "a green dot", good: "✓ On track" },
        { bad: "an amber bar", good: "36 min remaining" },
        { bad: "a red icon", good: "Eye drops not yet marked" },
      ],
    },
  },
  slider: {
    kicker: "The adaptive slider",
    heading: "Drag from the Healthy home to the Glaucoma home.",
    body: "Type scale 1.0 → 1.6, contrast up, spacing up, tap targets 44 → 64 px, thin rules thickening. At the midpoint the structure changes: the ring becomes one number, four cards become two, icons gain text labels.",
    label: "Interface adaptation, Healthy to Glaucoma",
    left: "Healthy",
    right: "Glaucoma",
    callouts: [
      { at: 0.15, text: "Larger type" },
      { at: 0.3, text: "One task at a time" },
      { at: 0.5, text: "Text and icon together" },
      { at: 0.65, text: "Large tap targets" },
      { at: 0.8, text: "No colour-only meaning" },
      { at: 0.95, text: "Important actions first" },
    ],
    closing: "Designed for clarity, not density.",
    rmToggleLabel: "Choose a configuration",
  },
  day: {
    kicker: "A day",
    heading: "Four prompts.",
    items: [
      { time: "8:00 AM", title: "Morning drops", body: "Time for your morning eye drops. Tap when done." },
      { time: "9:30 AM", title: "Bright light", body: "Sit by a window or step outside for 30 minutes." },
      { time: "8:00 PM", title: "Evening drops", body: "Time for your evening eye drops. Tap when done." },
      { time: "Day before", title: "Appointment tomorrow", body: "Eye clinic, 12 Oct at 10:30 AM. Bring your drops." },
    ],
  },
  config: {
    study: "ARKA Glaucoma",
    cohort: "Older adults with glaucoma",
    tabs: [
      { label: "Home", on: true },
      { label: "Insights", on: true, note: "simplified" },
      { label: "Inbox", on: true },
      { label: "Lumi", on: true, note: "large text" },
    ],
    targets: ["Daytime bright light 60 min", "Drops ×2 daily", "Appointments"],
    windows: ["Morning drops 8:00", "Bright light 9:30", "Evening drops 20:00"],
    lumi: true,
    typeScale: "1.6 · high contrast",
    arms: ["Single arm (designed)"],
  },
  decision: {
    n: 3,
    label: "Design decision",
    title: "Three things on screen.",
    lines: [
      "Primary actions on the home screen, flat navigation, no colour-only status.",
      "Each of these follows a published recommendation for older-adult interfaces; none has yet been tested with this cohort.",
    ],
    designRefs: ["older-adults-mhealth", "wcag22", "wcag-target-size"],
  },
  rationale: {
    button: "Design rationale",
    title: "Why this interface is sparse",
    paragraphs: [
      "Glaucoma reduces contrast sensitivity and peripheral vision. A dense screen becomes a search task. Three items, in order of importance, is the design response.",
      "Every tap target is at least 64 pixels: above the 44 px used elsewhere on the platform and well above the WCAG 2.2 minimum.",
      "Status is always written out. A person who cannot distinguish the green from the amber still reads '36 min remaining'.",
      "Lumi is kept, in large text, because a spoken-style conversation is often easier than a menu for this group. That is a hypothesis to test.",
    ],
    designRefs: ["older-adults-mhealth", "wcag-target-size", "wcag22"],
  },
  closing: "Designed for clarity, not density.",
};
