// Copy for /myopia. This is the only live configuration: mockups match the
// deployed app exactly and this is the only page allowed to say "deployed".

export const MYOPIA = {
  title: "ARKA · Myopia: children aged 7-12",
  header: {
    title: "Myopia",
    cohort: "Children aged 7-12",
    status: "live" as const,
    illustrationAlt: "A child in glasses running across a sunlit park while a parent follows with a phone.",
    ribbonLabel: "Light ribbon: outdoor minutes across the day",
    lede: "A parent sees numbers. A child sees a plant. The same wrist sensor drives both.",
  },
  goals: [
    { text: "120 minutes outdoors daily", refs: ["he2015", "xiong2017"] },
    { text: "+40 min/day at school slows progression", refs: ["he2015", "xiong2017"] },
    { text: "Prompting parents increases outdoor time", refs: ["li2022"] },
  ],
  loop: {
    kicker: "The loop",
    heading: "Less time outside, faster eye growth.",
    nodes: [
      { label: "Children spend more time indoors", refs: ["rose2008", "guggenheim2012"] },
      { label: "Miss daily light targets", refs: ["read2015"] },
      { label: "Accelerated axial elongation", refs: ["wu2018", "he2015"] },
      { label: "Myopia worsens", refs: ["dirani2009"] },
    ],
    body: "Each arrow is where an intervention could act. ARKA acts on the first two: it measures the light a child actually receives and prompts the parent while there is still daylight.",
  },
  parent: {
    kicker: "The parent's view",
    heading: "Numbers, for the person making decisions.",
    body: "The Home tab is the deployed screen. A sync banner confirms today's watch data arrived; a gauge shows outdoor minutes against the 120-minute target; the coaching line says exactly how many more minutes are needed.",
    callouts: [
      "Sync banner: today's watch data has been received.",
      "Gauge: 78 of 120 minutes, green up to the current value.",
      "Coaching line: how many more minutes, and why.",
    ],
    screen: {
      banner: "We've received today's watch data.",
      title: "Summary",
      sub: "Progress in daily light exposure",
      asOf: "Watch data as of 18 Sep 2026, 2:22 PM",
      gaugeLabel: "OUTDOOR",
      minutes: 78,
      target: 120,
      coachLead: "As of 18 Sep 2026, 2:22 PM, your child's outdoor time is:",
      coach: "Take your child outside for 42 more minutes to hit today's goal of 120 minutes!",
      coachSub: "For optimal myopia protection aim for 120 minutes outdoors per day.",
      wearTitle: "Monthly Wear Time (days)",
      tabs: ["Home", "Insights", "Plant", "Inbox"],
    },
  },
  plant: {
    kicker: "The plant",
    heading: "Growth, for the person whose behaviour is changing.",
    body: "The Plant tab is intervention-arm only. Scroll to scrub today's minutes from 0 to 180 and watch the traced sunflower grow through each threshold.",
    title: "Your plant",
    sub: "Grows with today's time outside",
    thresholds: [
      { p: 0, label: "0", title: "A seed in the soil", text: "A measured zero. The pot is not empty: the day has started and the watch is reporting." },
      { p: 0.15, label: "15", title: "First leaf at 15%", text: "18 minutes. The stem is procedural: it scales continuously with minutes: while the leaf is traced art." },
      { p: 0.4, label: "40", title: "Second leaf at 40%", text: "48 minutes. Leaves alternate sides. Every event is a fraction of target, never an absolute minute count." },
      { p: 0.65, label: "65", title: "Third leaf at 65%", text: "78 minutes: the same number the parent sees on the gauge." },
      { p: 0.85, label: "85", title: "Bud at 85%", text: "102 minutes. The shared bud is tinted with September's colour. It wiggles once when the goal is crossed live." },
      { p: 1, label: "100", title: "Bloom at 100%", text: "120 minutes. The September sunflower opens, a soft glow settles behind it and seven sparkles scatter. GOAL REACHED! in six rotating colours." },
      { p: 1.5, label: "150", title: "Beyond at 150%", text: "180 minutes. The glow widens, sparkles multiply, the head rocks gently, and the headline becomes AMAZING!" },
    ],
    minutesOutside: "minutes outside today",
    moreTo: (n: number) => `${n} more minutes to today's goal of 120.`,
    goalReached: "Goal reached!",
    goalSub: "Your plant is in full bloom for today.",
    amazing: "Amazing!",
    amazingSub: (n: number) => `${n} minutes outside today!`,
    stepperLabel: "Plant growth: percent of daily target",
  },
  garden: {
    kicker: "Twelve flowers, one garden",
    heading: "A different flower every month.",
    body: "The month comes from the study cycle date, not the device clock. A month is earned when the goal is met; a missed month stays as a faint silhouette; future months are locked.",
    gardenTitle: "My Garden · 2026",
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    earned: [true, true, false, true, true, true, true, true, true, false, false, false],
    currentMonth: 9,
    revealHeading: "All twelve.",
    revealBody: "Each is a collectible. Hover to lift it; select it to open its specimen card.",
    unlocked: "Unlocked",
    locked: "Not yet earned",
    specimenClose: "Close",
    yearInBloom: "A year in bloom",
    yearInBloomBody: "You've opened every flower.",
  },
  unlock: {
    kicker: "The unlock moment",
    heading: "Three frames.",
    body: "When the goal is crossed live, the bud wiggles, the flower pops and an overlay appears once per cycle date.",
    frames: [
      { label: "Wiggle", text: "The bud rotates ±9° for 450 ms." },
      { label: "Pop", text: "The head scales to 1.08 and settles over 1.1 s." },
      { label: "Overlay", text: "You did it!: September Sunflower unlocked: one amber button." },
    ],
    overlay: { title: "You did it!", sub: "September Sunflower unlocked", button: "Add to my garden" },
  },
  arms: {
    kicker: "Two groups",
    heading: "Intervention and comparison.",
    body: "We're testing whether the feedback loop changes behaviour: not assuming it does.",
    intervention: { title: "Intervention", items: ["Gauge", "Coaching line", "Plant tab"] },
    comparison: { title: "Comparison", items: ["Minutes only"] },
  },
  config: {
    study: "ARKA Myopia",
    cohort: "Children 7-12",
    tabs: [
      { label: "Home", on: true },
      { label: "Insights", on: true },
      { label: "Plant", on: true, note: "intervention only" },
      { label: "Inbox", on: true },
      { label: "Updates", on: true },
      { label: "Lumi", on: false },
    ],
    targets: ["120 min outdoors"],
    windows: ["Afternoon nudge while daylight remains"],
    lumi: false,
    typeScale: "1.0",
    arms: ["Intervention", "Comparison"],
  },
  decision: {
    n: 1,
    label: "Design decision",
    title: "Numbers for parents. Growth for children.",
    lines: [
      "The same sensor data, represented differently for the person making decisions and the person whose behaviour is changing.",
      "The parent needs a number to act on; the child needs a reason to want to go outside.",
    ],
  },
  rationale: {
    button: "Design rationale",
    title: "Why two interfaces",
    paragraphs: [
      "The parent decides when the child goes outside, so the parent's screen is a decision tool: today's minutes, the gap to target, and exactly what to do next.",
      "The child does not need a target. The child needs a reason. The plant turns 120 minutes into a bloom without ever showing a chart.",
      "Both views read from the same sensor record. Nothing is estimated for the child that is not also visible to the parent.",
      "The plant is intervention-arm only. The comparison arm sees minutes and nothing else, so the study can ask whether the feedback loop itself changes behaviour.",
    ],
  },
  closing: "One sensor. Two audiences. The interface is the intervention.",
};
