// scripts/extract-flower-art.ts
//
// One-off asset extraction (spec §13). Run with:
//   npm run assets:flowers
//
// WHAT IT DID
//   Read the traced plant artwork (twelve monthly flower heads, the shared
//   bud, pot and leaf) from the deployed app's generated table — read-only,
//   nothing in that repo is touched — and wrote it into this repo in two forms:
//
//   1. public/assets/flowers/<name>.svg
//      Standalone SVGs, one per asset, viewBox tightened to the traced
//      content box so every head shares a centre and apparent diameter.
//
//   2. src/lib/flowerArt.core.gen.ts  (sunflower, bud, pot, leaf — used on
//      the About page and every Myopia plant scene) and
//      src/lib/flowerArt.extra.gen.ts (the other eleven monthly heads,
//      loaded lazily by the Myopia garden). Same path data, same content
//      boxes, same `tint` flags on the bud petals, so the site's plant is
//      geometrically identical to the deployed one.
//
// The only reference to the app repo lives in this script. src/ never
// imports from it (verified in §17: grep -r "light-balance" src/ is empty).

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const SOURCE = join(homedir(), "dev/light-balance-app/lib/plantFlowerArt.gen.ts");
const ROOT = join(import.meta.dirname, "..");
const SVG_OUT = join(ROOT, "public/assets/flowers");
const TS_CORE = join(ROOT, "src/lib/flowerArt.core.gen.ts");
const TS_EXTRA = join(ROOT, "src/lib/flowerArt.extra.gen.ts");

type ArtPath = { d: string; fill: string; tint?: boolean };
type Art = { key: string; box: [number, number, number, number]; paths: ArtPath[] };

const src = readFileSync(SOURCE, "utf8");

// Parse `export const ART_X: FlowerArt = Object.freeze({ box: [...], paths: [ {...}, ] });`
const blockRe =
  /export const ART_([A-Z]+): FlowerArt = Object\.freeze\(\{\s*box: \[([^\]]+)\] as const,\s*paths: \[([\s\S]*?)\n  \],\s*\}\);/g;
const pathRe = /\{ d: "((?:[^"\\]|\\.)*)", fill: "([^"]+)"(, tint: true)? \}/g;

const KEY_MAP: Record<string, string> = {
  CAMELLIA: "camellia",
  TULIP: "tulip",
  DAFFODIL: "daffodil",
  CHERRY: "cherry",
  ROSE: "rose",
  ORCHID: "orchid",
  MORNINGGLORY: "morningGlory",
  HIBISCUS: "hibiscus",
  SUNFLOWER: "sunflower",
  MARIGOLD: "marigold",
  CHRYSANTHEMUM: "chrysanthemum",
  POINSETTIA: "poinsettia",
  BUD: "bud",
  POT: "pot",
  LEAF: "leaf",
};

const arts: Art[] = [];
for (const m of src.matchAll(blockRe)) {
  const key = KEY_MAP[m[1]];
  if (!key) continue;
  const box = m[2].split(",").map((n) => Number(n.trim())) as [number, number, number, number];
  const paths: ArtPath[] = [];
  for (const p of m[3].matchAll(pathRe)) {
    const item: ArtPath = { d: p[1].replace(/\\"/g, '"').replace(/\\\\/g, "\\"), fill: p[2] };
    if (p[3]) item.tint = true;
    paths.push(item);
  }
  arts.push({ key, box, paths });
}

if (arts.length !== 15) {
  throw new Error(`Expected 15 art assets, parsed ${arts.length}`);
}

// 1. Standalone SVGs
mkdirSync(SVG_OUT, { recursive: true });
for (const a of arts) {
  const [x, y, w, h] = a.box;
  const body = a.paths.map((p) => `<path fill="${p.fill}" d="${p.d}"/>`).join("\n  ");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x} ${y} ${w} ${h}" role="img" aria-label="${a.key}">\n  ${body}\n</svg>\n`;
  writeFileSync(join(SVG_OUT, `${a.key}.svg`), svg);
}

// 2. TypeScript modules
const CORE = new Set(["sunflower", "bud", "pot", "leaf"]);
function emit(list: Art[], file: string, header: string) {
  const lines: string[] = [
    `// ${file.split("/").slice(-1)[0]}`,
    "// GENERATED by scripts/extract-flower-art.ts — do not edit by hand.",
    `// ${header}`,
    "// Coordinates are in the original 1024x1024 trace space; `box` is the tight",
    "// content box [x, y, w, h] used to normalise every head to a shared centre.",
    "",
    'import type { FlowerArt } from "./flowerArtTypes";',
    "",
  ];
  for (const a of list) {
    lines.push(`export const ART_${a.key.toUpperCase()}: FlowerArt = {`);
    lines.push(`  box: [${a.box.join(", ")}],`);
    lines.push("  paths: [");
    for (const p of a.paths) {
      const d = p.d.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      lines.push(`    { d: "${d}", fill: "${p.fill}"${p.tint ? ", tint: true" : ""} },`);
    }
    lines.push("  ],");
    lines.push("};");
    lines.push("");
  }
  writeFileSync(file, lines.join("\n"));
}

emit(
  arts.filter((a) => CORE.has(a.key)),
  TS_CORE,
  "Core plant art: September sunflower, shared bud, pot and leaf.",
);
emit(
  arts.filter((a) => !CORE.has(a.key)),
  TS_EXTRA,
  "The other eleven monthly flower heads. Loaded lazily by the Myopia garden.",
);

console.log(`Wrote ${arts.length} SVGs to public/assets/flowers/ and two TS modules.`);
